NIEHS/chords-health-dictionary:
  - source: schema/gdcdictionary/schemas
    dest: gdcdictionary/schemas

NIEHS/cdis-manifest:
  - source: custom_configs/gitops.json
    dest: staging.chords-health.org/portal/gitops.json
  - source: custom_configs/etlMapping.yaml
    dest: staging.chords-health.org/etlMapping.yaml