global:
  hostname: "localhost"
  dictionaryUrl: https://raw.githubusercontent.com/NIEHS/pcor_gen3_artifacts/feature/36-add-gen3-gitops-automations/custom_configs/schema.json

sower:
  enabled: false

hatchery:
  enabled: false

# disabling audit service
audit:
  enabled: false

# disabling argo-wrapper service
argo-wrapper:
  enabled: false