global:
  hostname: "localhost"
  dictionaryUrl: https://raw.githubusercontent.com/NIEHS/pcor_gen3_artifacts/develop/custom_configs/schema.json

sower:
  enabled: false

hatchery:
  enabled: false

# disabling audit service
audit:
  enabled: false

# disabling argo-wrapper service
argo-wrapper:
  enabled: false

sheepdog:
  enabled: true
  volumeMounts:
    - name: "config-volume"
      readOnly: true
      mountPath: "/var/www/sheepdog/settings.py"
      subPath: "wsgi.py"

peregrine:
  enabled: true
  volumeMounts:
    - name: "config-volume"
      readOnly: true
      mountPath: "/var/www/peregrine/wsgi.py"
      subPath: "settings.py"