global:
  hostname: "localhost"
  dictionaryUrl: https://raw.githubusercontent.com/NIEHS/pcor_gen3_artifacts/feature/lara-model/custom_configs/schema.json

sower:
  enabled: false

hatchery:
  enabled: false

# disabling audit service
audit:
  enabled: false

# disabling argo-wrapper service
argo-wrapper:
  enabled: false

etl:
  image:
    # patch to flatten nested array
    tube:
      # -- (string) Overrides the image tag whose default is the chart appVersion.
      tag: "1.0.4"