global:
  hostname: "localhost"
<<<<<<< HEAD
  dictionaryUrl: https://raw.githubusercontent.com/NIEHS/pcor_gen3_artifacts/feature/lara-model/custom_configs/schema.json
=======
  dictionaryUrl: https://raw.githubusercontent.com/NIEHS/pcor_gen3_artifacts/feature/40-update-temporal_resolution/custom_configs/schema.json
>>>>>>> d0fc055 ( #40 update temporal_resolution)


sower:
  enabled: false

hatchery:
  enabled: false

# disabling audit service
audit:
  enabled: false

# disabling argo-wrapper service
argo-wrapper:
  enabled: false

etl:
  image:
    # patch to flatten nested array
    tube:
      # -- (string) Overrides the image tag whose default is the chart appVersion.
      tag: "1.0.4"