# This workflow will trigger dump_schema.py which dumps all the schema files in gdcdictionary 
# folder to one json schema
name: Dump Schema
run-name: ${{ github.actor }} pushed new upadate

on:
  push:
    branches: [  feature/action-dump-schema ]
    paths:
    - 'schemas/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.7" #install the python needed
      - name: Install dependencies
        run: |
          python setup.py install
      - name: Execute dump schema
        id: script
        run: |
          python pcor_gen3_artifacts/schema/dump_schema.py
      - name: Print errors
        if: steps.script.outputs.error == 'true'
        run: |
          printenv "SCRIPT_STDOUT"
          printenv "SCRIPT_STDERR"
        env:
          SCRIPT_STDOUT: ${{ steps.script.outputs.stdout }}
          SCRIPT_STDERR: ${{ steps.script.outputs.stderr }} 
      - name: Commit and push changes
        run: |
          git config --global user.name "pateldes"
          git config --global user.email "deeppatel.cs@gmail.com"

          git add -A
          git commit -m "commit message"
          git push
