# This workflow will trigger generate_gen3_gitops_values.py when config files are updated
# it will create 5 yaml files in gen3_gitops/values folder
name: Generate gen3 gitops Values
run-name: Generate new gen3 gitops Values ${{ github.actor }} updated config files
on:
  push:
    paths: custom_configs/**
jobs:
  Generate-new-gen3-gitops-values:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Current branch name
        run: |
          echo "${{ steps.branch-name.outputs.current_branch }}"
      - name: checkout repo content and branch on which change is pushed # checkout the repository content to github runner.
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.branch-name.outputs.current_branch }}
      - name: List files
        run: ls
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9" #install the python needed

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install pcor_tools
        run: |
          cd pcor_tools
          python setup.py install

      - name: Execute generate gen3 gitops values
        id: script
        run: |
          cd pcor_tools
          python generate_gen3_gitops_values.py

      - name: Print errors
        if: steps.script.outputs.error == 'true'
        run: |
          printenv "SCRIPT_STDOUT"
          printenv "SCRIPT_STDERR"
        env:
          SCRIPT_STDOUT: ${{ steps.script.outputs.stdout }}
          SCRIPT_STDERR: ${{ steps.script.outputs.stderr }}

      - name: Update dictionaryUrl
        run: |
          sed -i -e 's|NIEHS/pcor_gen3_artifacts/develop|NIEHS/pcor_gen3_artifacts/${{ steps.branch-name.outputs.current_branch }}|' gen3-gitops/values/values.yaml

      - name: Commit and push changes
        run: |
          git pull
          git config --global user.name "pateldes"
          git config --global user.email "deeppatel.cs@gmail.com"

          git add -A
          git commit -m "#1 (github_action: Generate gen3 gitops Values) update values in gen3-gitops"
          git push